services:
  postgres:
    image: postgres:16-alpine
    container_name: knowledge-box-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=knowledgebox
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - knowledge-box-network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowledge-box-auth-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=knowledgebox;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    networks:
      - knowledge-box-network

volumes:
  postgres-data:
    name: knowledge-box-postgres-data

networks:
  knowledge-box-network:
    name: knowledge-box-network 